version: '3'

services:
  rails:
    container_name: is-project2-rails
    build:
      dockerfile: docker/development/Dockerfile
      context: .
    env_file: .env
    entrypoint: ./docker/development/entrypoint.sh

    stdin_open: true
    tty: true
    volumes:
      - .:/project
      - bundle_data:/bundle
      - $HOME/.ssh:/project/docker/development/home/.ssh
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - sidekiq

  postgres:
    image: postgres:13
    container_name: is-project2-postgres
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: "is-project2-redis"
    image: redis
    restart: always
    ports:
      - 6379:6379

  sidekiq:
    container_name: is-project2-sidekiq
    image: rails
    user: "${UID}:${GID}"
    build:
      dockerfile: docker/development/Dockerfile
      context: .
    entrypoint: ./docker/development/entrypoint_sidekiq.sh
    volumes:
      - .:/project
      - /project/tmp
    env_file: .env

volumes:
  bundle_data:
  postgres_data:
  redis_data:
