# frozen_string_literal: true

unless Place.any?
  STDOUT.puts("Seeding DB with Places")

  Place.create([
    { name: "Alto Minho" },
    { name: "Abrantes" },
    { name: "Águeda" },
    { name: "Amadora" },
    { name: "Angra do Heroísmo" },
    { name: "Arco de Baúlhe" },
    { name: "Aveiras de Cima" },
    { name: "Beja" },
    { name: "Braga" },
    { name: "Bragança" },
    { name: "Carapinheira" },
    { name: "Carregado/Alenquer" },
    { name: "Castelo Branco" },
    { name: "Castro Verde" },
    { name: "Chaves" },
    { name: "Côa" },
    { name: "Coimbra" },
    { name: "Costa do Estoril" },
    { name: "Elvas" },
    { name: "Estremoz" },
    { name: "Fafe" },
    { name: "Faro" },
    { name: "Figueira da Foz" },
    { name: "Foz Tejo" },
    { name: "Frazão" },
    { name: "Gandarela" },
    { name: "Guimarães" },
    { name: "Leiria" },
    { name: "Lisboa" },
    { name: "Lourinhã" },
    { name: "Macieira de Rates" },
    { name: "Maia" },
    { name: "Maiorca" },
    { name: "Matosinhos" },
    { name: "Ovar" },
    { name: "Portalegre" },
    { name: "Portimão" },
    { name: "Porto" },
    { name: "Póvoa de Varzim" },
    { name: "Rio Maior" },
    { name: "Sanguedo" },
    { name: "Setúbal" },
    { name: "Sobreira" },
    { name: "Tavira" },
    { name: "Vale de Cambra" },
    { name: "Valença" },
    { name: "Vila Nova de Gaia" },
    { name: "Vila Real" },
    { name: "Vilar Formoso" },
    { name: "Vila Viçosa" },
    { name: "Viseu" },
  ])
end
