default: &default
  adapter: postgresql
  encoding: unicode
  pool: "<%= ENV.fetch('RAILS_MAX_THREADS', 5) %>"
  host: "<%= ENV.fetch('DATABASE_HOST', 'postgres') %>"
  port: "<%= ENV.fetch('DATABASE_PORT', '5432') %>"
  username: "<%= ENV.fetch('DATABASE_USERNAME', 'useradmin') %>"
  password: "<%= ENV.fetch('DATABASE_PASSWORD', 'useradmin') %>"

development:
  <<: *default
  database: "<%= ENV.fetch('DATABASE_NAME', 'is_project2_development') %>"

test:
  <<: *default
  database: is_project2_test

production:
  <<: *default
  database: "<%= ENV.fetch('DATABASE_NAME', 'is_project2_production') %>"
